language: node_js
node_js:
  - "lts/*"
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_fcee4a8e5699_key -iv $encrypted_fcee4a8e5699_iv
    -in .travis/travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - yarn global add hexo-cli
  - yarn install
  - git clone --depth 1 --branch v7.2.0 https://github.com/theme-next/hexo-theme-next.git themes/next
script:
  - hexo clean
  - hexo generate
  - rsync -az -vv --delete -e "ssh -o 'StrictHostKeyChecking no' -p $PORT" public/ travis@$HOST:/var/www/blog
  - rm -rf ~/.ssh
