# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "NiBo's Blog"
subtitle: "It's now or never."
description: ""
keywords: ""
author: NiBo
language: zh-CN
timezone: "Asia/Shanghai"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://nibo.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page


# Post wordcount display settings
# Dependencies: https://github.com/theme-next/hexo-symbols-count-time
# symbols_count_time:
#   symbols: true
#   time: false
#   total_symbols: true
#   total_time: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
theme_config:
  favicon:
    small: /images/favicon.ico
    medium: /images/favicon.ico
    apple_touch_icon: /images/favicon.ico
    safari_pinned_tab: /images/favicon.ico
  avatar:
    url: /images/avatar.png
    # If true, the avatar would be dispalyed in circle.
    rounded: true
    # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
    opacity: 0.8
    # If true, the avatar would be rotated with the cursor.
    rotated: true
  menu:
    首页: / || home
    #about: /about/ || user
    标签: /tags/ || tags
    分类: /categories/ || th
    归档: /archives/ || archive
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat
  # Post meta display settings
  post_meta:
    item_text: true
    created_at: true
    # updated_at:
    #   enabled: true
    #   another_day: true
    categories: true
  font:
    enable: true
    global:
      external: true
      family: 'Noto Sans SC'
      size:
    logo:
      external: true
      family: Eater
      size: 36
    codes:
      external: true
      family: 'Roboto Mono'
      size:
  sidebar:
    scrollpercent: true
  scheme: Gemini
  fancybox: true
  # Disqus
  disqus:
    enable: true
    shortname: nibo
    count: true
    lazyload: true
  firestore:
    enable: true
    collection: visitors #required, a string collection name to access firestore database
    apiKey: AIzaSyCPkbwn8R0zcGZ7NRA6zxHt4IzCieLq2vc #required
    projectId: nibo-blog #required
    bluebird: false #enable this if you want to include bluebird 3.5.1(core version) Promise polyfill
  vendors:
    _internal: lib
    fancybox: //cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.6/jquery.fancybox.min.js
    fancybox_css: //cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# deploy:
#   type: git
#   repo: git@github.com:nibocn/nibocn.github.com.git
#   branch: [master]
