name: Blog Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Add theme
        run: |
          git clone --depth 1 https://github.com/theme-next/hexo-theme-next.git themes/next
      - name: Install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependences
        run: |
          npm install -g hexo-cli
          npm install
      - name: Generate blog
        run: |
          npm run clean
          npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: public/
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          TARGET: ${{ secrets.DEPLOY_DIR }}
